name: Test Project
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "01-basics/react-basic/**"


jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./01-basics/react-basic

    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test